#include<stdio.h>
#include<conio.h>
#include<math.h>
#include<string.h>
void main()
{
clrscr();
char name[30];
int empId;
float salary;
}
printf("\n enter employee details:\n");
printf("please enter employe Id:\n");
gets(emp name);
printf("please enter the employee Id:\n");
scanf("%d",&emp.empId);
printf("please enter the salary:\n");
scanf("%f",&emp.salary);
printf("entered employe deteails are:\n");
printf("______\n");
printf("name:%s\n",emp name);
printf("id:%d\n",emp empid);
printf("salary:%f\n",emp salary);
getch();
}